[workspace]
members = [
    "crates/*"
]

resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
derive_more = "0.99"
once_cell = "1"
rustc-hash = "1"
thin-vec = "0.2"

[profile.release]
opt-level = 3
lto = true
strip = true
