[package]
name = "syphon"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }

syphon_errors = { path = "../errors" }
syphon_lexer = { path = "../lexer" }
syphon_parser = { path = "../parser" }
