[package]
name = "syphon_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thin-vec = { workspace = true }

syphon_ast = { path = "../ast" }
syphon_errors = { path = "../errors" }
syphon_lexer = { path = "../lexer" }
