[package]
name = "syphon_bytecode"
version = "0.1.0"
edition = "2021"

[dependencies]
thin-vec = { workspace = true }
derive_more = { workspace = true }

syphon_ast = { path = "../ast" }
syphon_errors = { path = "../errors" }
syphon_parser = { path = "../parser" }
